drop schema if exists orgb cascade ;
drop schema if exists orgc cascade ;
drop schema if exists og cascade;
drop schema if exists org_group cascade;

delete from entity_approval_status;
delete from encounter;
delete from program_encounter;
delete from program_enrolment;
delete from individual;
delete from gender where id > 3;
delete from entity_sync_status;
delete from index_metadata;
delete from column_metadata;
delete from table_metadata;
delete from form_mapping;
delete from form_element;
delete from form_element_group;
delete from decision_concept;
delete from form;
delete from concept_answer;
delete from answer_concept_migration;
delete from concept;
delete from operational_encounter_type;
delete from encounter_type;
delete from operational_program;
delete from program;
delete from operational_subject_type;
delete from subject_type;
delete from catchment_address_mapping;
delete from address_level;
delete from address_level_type;
delete from users where organisation_id >= 10;

delete from organisation_group_organisation where organisation_id >= 10;
delete from organisation_group where id >= 10;
delete from organisation where id >= 10;
