INSERT INTO table_metadata (id, name, type, schema_name, subject_type_uuid, program_uuid, encounter_type_uuid, form_uuid) VALUES (312, 'person', 'Person', 'orgc', 'a95d8951-17e4-408d-98b0-ef3a6c982b96', null, null, 'e237b92c-64a5-4bd6-b595-7668cb0ba111');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5243, 312, 'id', 'integer', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5244, 312, 'uuid', 'text', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5245, 312, 'is_voided', 'bool', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5246, 312, 'created_by_id', 'integer', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5247, 312, 'last_modified_by_id', 'integer', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5248, 312, 'created_date_time', 'timestampWithTimezone', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5249, 312, 'last_modified_date_time', 'timestampWithTimezone', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5250, 312, 'address_id', 'integer', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5251, 312, 'registration_date', 'date', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5252, 312, 'first_name', 'text', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5253, 312, 'last_name', 'text', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5254, 312, 'registration_location', 'point', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5255, 312, 'legacy_id', 'text', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5256, 312, 'latest_approval_status', 'text', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5257, 312, 'date_of_birth', 'date', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5258, 312, 'date_of_birth_verified', 'bool', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5259, 312, 'gender', 'text', null, null, null, 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5260, 312, 'Question group Child 2', 'text', 107582, 'Text', 'eead9471-d160-42c0-a237-ea3ba20821ae', 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5261, 312, 'Question group Child 1', 'text', 107581, 'Text', '62412d21-85a2-4bfa-9e74-1c21395235b9', 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5262, 312, 'Duration Question', 'text', 107571, 'Duration', '73180110-f639-411e-9d6d-b6a0f6c9fa3b', 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5263, 312, 'DateTime Question', 'timestamp', 107572, 'DateTime', '847e0304-f0ca-47a8-91cc-615aa941a7e7', 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5264, 312, 'Date Question', 'date', 107570, 'Date', '60faf754-baf0-4019-9b4d-43bc2ae72f1e', 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5265, 312, 'Multi Select Question', 'text', 107569, 'MultiSelect', '6f44737e-5bc5-4513-ac70-89697cedbc96', 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5266, 312, 'Single Select Question', 'text', 107565, 'SingleSelect', 'b6f63312-ae34-4405-9a6f-80aa5a9f0aab', 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5267, 312, 'Text Question', 'text', 107561, 'Text', '701b68df-dc52-4d69-ab91-f03a70ac1bbc', 'orgc');
INSERT INTO column_metadata (id, table_id, name, type, concept_id, concept_type, concept_uuid, schema_name) VALUES (5268, 312, 'Numeric Question', 'numeric', 107560, 'Numeric', 'f005ccf7-f714-4615-a2a0-26efa2da6491', 'orgc');
insert into index_metadata(id, table_metadata_id, column_id, name) VALUES (1, 312, 5243, 'orgc_12344_idx');
insert into index_metadata(id, table_metadata_id, column_id, name) VALUES (2, 312, 5244, 'orgc_12345_idx');